pipeline {
    agent any

    stages {
        stage('Get Recommendations') {

            steps {
                echo " least_privilege_option: ${params.'least_privilege_option'}"
                echo " entities: ${params.'entities'}"
                echo " channel name: ${params.'channel_name'}"
                echo " user id: ${params.'user_id'}"
            }
        }
       stage('Apply Fixes') {

         steps { 
              script {

                 blocks = [
                            [
                                "type": "section",
                                "text": [
                                    "type": "mrkdwn",
                                    "text": "Fix for ${params.'least_privilege_option'} have been applied to the following entities:\n ${params.'entities'}"
                                ]
                            ],
                            [
                                "type": "context",
                                "elements": [
                                    [
                                        "type": "mrkdwn",
                                        "text": "*<@${params.'user_id'}>* has approved this action"
                                    ]
                                ]
                            ]
                        ]

                    slackSend (
                        color: "warning",
                        blocks: blocks,
                        channel: "#${params.'channel_name'}"
                    )
              }
           }
        }
    }
}
